version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_PASSWORD: gitpod
      POSTGRES_DB: gitpoddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data:
